language: rust
sudo: false

rust:
  - 1.31.0  # Minimum supported version
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

install:
  - rustup component add clippy-preview
  - rustc -V
  - cargo -V
  - cargo clippy -V

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo clean
  - cargo build --verbose --features use_core
  - cargo test --verbose --features use_core
  - cargo clippy --verbose --features use_core

  # `compiletest_rs` 0.3.14 is not compatible with `-Z minimal-versions`, so do
  # not use the "test-nightly" feature
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then cargo update -Z minimal-versions; fi
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then cargo build --verbose; fi
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then cargo test --verbose; fi
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then cargo build --features=use_core; fi
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then cargo test --verbose --features=use_core; fi
