language: rust
sudo: false

rust:
  - 1.34.0  # Minimum supported version
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

install:
  # Some toolchains don't ship clippy, so handle this case to not break the build
  - if rustup component add clippy-preview; then export HAS_CLIPPY=true; else export HAS_CLIPPY=false; fi
  - rustc -V
  - cargo -V
  - if ${HAS_CLIPPY}; then cargo clippy -V; fi

script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo clean
  - cargo build --verbose --features=use_core
  - cargo test --verbose --features=use_core
  - if ${HAS_CLIPPY}; then cargo clippy --verbose --features=use_core; fi

  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then cargo update -Z minimal-versions; fi
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then cargo build --verbose; fi
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then cargo test --verbose; fi
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then cargo build --features=use_core; fi
  - if [ ${TRAVIS_RUST_VERSION} = "nightly" ]; then cargo test --verbose --features=use_core; fi

  - if [ ${TRAVIS_RUST_VERSION} = "stable" ]; then cargo test compile_test -- --ignored; fi